routes/web.php
    Route::get('shipping_carrier_mapping/{customer}/carriers', 'CustomerShippingCarriersMapController@carriers');
    Route::get('shipping_carrier_mapping/{customer}/{service}/mapped_carriers', 'CustomerShippingCarriersMapController@mappedCarriers');
    Route::resource('shipping_carrier_mapping', 'CustomerShippingCarriersMapController');

    Route::get('shipping_method_mapping/data_table', 'CustomerShippingMethodsMapController@dataTable');
    Route::get('shipping_method_mapping/filter_customers', 'CustomerShippingMethodsMapController@filterCustomers')->name('shipping_method_mapping.filter_customers');
    Route::get('shipping_method_mapping/{customer}/carrier/{carrier}', 'CustomerShippingMethodsMapController@carrier');
    Route::resource('shipping_method_mapping', 'CustomerShippingMethodsMapController');

    Route::get('shipping_boxes/data_table', 'ShippingBoxController@dataTable')->name('shipping_boxes.data_table');
    Route::get('shipping_boxes/{shipping_box}/preview', 'ShippingBoxController@preview')->name('shipping_boxes.preview');
    Route::get('shipping_boxes/{shipping_box}/editable_preview', 'ShippingBoxController@editablePreview')->name('shipping_boxes.editable_preview');
    Route::resource('shipping_boxes', 'ShippingBoxController');

    Route::get('location_types/data_table/{three_pl?}', 'LocationTypeController@dataTable')->name('location_types.data_table');
    Route::get('location_types/{location_type}/preview', 'LocationTypeController@preview')->name('location_types.preview');
    Route::get('location_types/{location_type}/editable_preview', 'LocationTypeController@editablePreview')->name('location_types.editable_preview');
    Route::get('location_types/filter_3pls', 'LocationTypeController@filter3Pls')->name('location_types.filter_3pls');
    Route::resource('location_types', 'LocationTypeController');

    Route::get('shipping_carriers/{shipping_carrier}/preview', 'ShippingCarrierController@preview')->name('shipping_carriers.preview');
    Route::get('shipping_carriers/{shipping_carrier}/editable_preview', 'ShippingCarrierController@editablePreview')->name('shipping_carriers.editable_preview');
    Route::get('shipping_carriers/data_table', 'ShippingCarrierController@dataTable')->name('shipping_carriers.data_table');
    Route::get('shipping_carriers/{shipping_carrier}/shipping_methods', 'ShippingCarrierController@shippingMethods')->name('shipping_carriers.shipping_methods');
    Route::get('shipping_carriers/filter_3pls', 'ShippingCarrierController@filter3Pls')->name('shipping_carriers.filter_3pls');

    Route::resource('shipping_carriers', 'ShippingCarrierController');

    Route::get('shipping_methods/{shipping_method}/preview', 'ShippingMethodController@preview')->name('shipping_methods.preview');
    Route::get('shipping_methods/{shipping_method}/editable_preview', 'ShippingMethodController@editablePreview')->name('shipping_methods.editable_preview');
    Route::get('shipping_methods/data_table', 'ShippingMethodController@dataTable')->name('shipping_method.data_table');
    Route::get('shipping_methods/get_carriers/{three_pl?}', 'ShippingMethodController@getShippingCarriers')->name('shipping_method.get_carriers');
    Route::resource('shipping_methods', 'ShippingMethodController');

    Route::get('api_logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::get('billing_profiles/data_table', 'BillingProfileController@dataTable')->name('billing_profiles.data_table');
    Route::resource('billing_profiles', 'BillingProfileController');
    Route::post('billing_profiles/{id}/clone', 'BillingProfileController@clone')->name('billing_profiles.clone');

    Route::get('billings', 'BillingController@index')->name('billings.index');
    Route::get('billings/customers', 'BillingController@customers')->name('billings.customers');
    Route::get('billings/customers/{customer}/bills', 'BillingController@customerBillsEdit')->name('billings.customer_bills');
    Route::get('billings/customers/{customer}/bills/data_table', 'BillingController@customerBillsDataTable');
    Route::get('billings/customers/{customer}/bills/{bill}/items', 'BillingController@customerBillItems')->name('billings.customer_bill_items');

    Route::get('billings/customers/bills/{bill}/items/unbilled', 'BillingController@unbilled')->name('billings.unbilled');
    Route::get('bills/{bill}/unbilled_shipments', 'BillingController@unBilledShipments');
    Route::get('bills/{bill}/unbilled_purchase_orders', 'BillingController@unBilledPurchaseOrders');
    Route::get('bills/{bill}/unbilled_purchase_order_items', 'BillingController@unBilledPurchaseOrderItems');
    Route::get('bills/{bill}/unbilled_locations', 'BillingController@unBilledLocations');
    Route::get('bills/{bill}/unbilled_packages', 'BillingController@unBilledPackages');
    Route::get('bills/{bill}/unbilled_package_items', 'BillingController@unBilledPackageItems');
    Route::get('bills/{bill}/unbilled_inventory_changes', 'BillingController@unBilledInventoryChanges');
    Route::get('bills/{bill}/return_items', 'BillingController@unBilledReturnItems');

    Route::get('billings/bills', 'BillingController@bills')->name('billings.bills');
    Route::get('billings/bills/data_table', 'BillingController@billsDataTable');

    Route::get('billings/billing_profiles', 'BillingController@billingProfiles')->name('billings.billing_profiles');
    Route::get('billings/reconcile', 'BillingController@reconcile')->name('billings.reconcile');
    Route::get('billings/exports', 'BillingController@exports')->name('billings.exports');
    Route::get('billings/product_profiles', 'BillingController@productProfiles')->name('billings.product_profiles');

    Route::get('invoices/data_table', 'InvoiceController@dataTable')->name('invoices.data_table');
    Route::get('invoices/invoice_statuses', 'InvoiceController@invoiceStatuses')->name('invoices.invoice_statuses');
    Route::get('invoices/{direct_url}', 'InvoiceController@view')->name('invoice.direct_url');
    Route::get('invoices/{invoice}/print_preview', 'InvoiceController@print_preview')->name('invoices.print_preview');
    Route::get('invoices/{invoice}/preview', 'InvoiceController@preview')->name('invoices.preview');
    Route::get('invoices/{invoice}/editable_preview', 'InvoiceController@editablePreview')->name('invoices.editable_preview');
    Route::resource('invoices', 'InvoiceController');

    Route::get('invoice_statuses/filter_customers', 'InvoiceStatusController@filterCustomers')->name('invoice_statuses.filter_customers');
    Route::resource('invoice_statuses', 'InvoiceStatusController');

    Route::get('product_profiles/data_table', 'ProductProfileController@dataTable');
    Route::get('product_profiles/product_data_table/{product_profile}', 'ProductProfileController@productDataTable');
    Route::get('product_profiles/{product_profile}/product_list', 'ProductProfileController@productList');
    Route::post('product_profiles/{product_profile}/save_product_selection', 'ProductProfileController@saveProductSelection');
    Route::resource('product_profiles', 'ProductProfileController');

    Route::get('billing_fees/data_table', 'BillingFeeController@dataTable');
    Route::get('billing_fees', 'BillingFeeController@index');
    Route::get('billing_fees/billing_profile/{billing_profile}/add_fee/{type}', 'BillingFeeController@create')->name('billing_fees.create');
    Route::get('billing_fees/billing_profile/{billing_profile}/billing_fee/{billing_fee}/edit', 'BillingFeeController@edit')->name('billing_fees.edit');

    Route::post('billing_fees/billing_profile/{billing_profile}/add_fee/recurring', 'BillingFeeController@recurringStore')->name('billing_fees.recurring.store');
    Route::post('billing_fees/billing_profile/{billing_profile}/update_fee/{billing_fee}/recurring', 'BillingFeeController@recurringUpdate')->name('billing_fees.recurring.update');

    Route::post('billing_fees/billing_profile/{billing_profile}/add_fee/receiving_by_hour', 'BillingFeeController@receivingByHourStore')->name('billing_fees.receiving_by_hour.store');
    Route::post('billing_fees/billing_profile/{billing_profile}/update_fee/{billing_fee}/receiving_by_hour', 'BillingFeeController@receivingByHourUpdate')->name('billing_fees.receiving_by_hour.update');


    Route::post('billing_fees/billing_profile/{billing_profile}/add_fee/receiving_by_po', 'BillingFeeController@receivingByPoStore')->name('billing_fees.receiving_by_po.store');
    Route::post('billing_fees/billing_profile/{billing_profile}/update_fee/{billing_fee}/receiving_by_po', 'BillingFeeController@receivingByPoUpdate')->name('billing_fees.receiving_by_po.update');

    Route::post('billing_fees/billing_profile/{billing_profile}/add_fee/receiving_by_item', 'BillingFeeController@receivingByItemStore')->name('billing_fees.receiving_by_item.store');
    Route::post('billing_fees/billing_profile/{billing_profile}/update_fee/{billing_fee}/receiving_by_item', 'BillingFeeController@receivingByItemUpdate')->name('billing_fees.receiving_by_item.update');

    Route::post('billing_fees/billing_profile/{billing_profile}/add_fee/receiving_by_line', 'BillingFeeController@receivingByLineStore')->name('billing_fees.receiving_by_line.store');
    Route::post('billing_fees/billing_profile/{billing_profile}/update_fee/{billing_fee}/receiving_by_line', 'BillingFeeController@receivingByLineUpdate')->name('billing_fees.receiving_by_line.update');

    Route::post('billing_fees/billing_profile/{billing_profile}/add_fee/storage_by_location', 'BillingFeeController@storageByLocationStore')->name('billing_fees.storage_by_location.store');
    Route::post('billing_fees/billing_profile/{billing_profile}/update_fee/{billing_fee}/storage_by_location', 'BillingFeeController@storageByLocationUpdate')->name('billing_fees.storage_by_location.update');

app/Http/Controllers/BillingController.php
<?php

namespace App\Http\Controllers;

use App\Components\BillComponent;
use App\Http\Resources\BillsTableResource;
use App\Http\Resources\CustomerBillsTableResource;
use App\Models\Bill;
use App\Models\BillingFee;
use App\Models\Customer;
use App\Models\Shipment;
use App\Models\ShippingCarrier;
use App\Models\ShippingMethod;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;

class BillingController extends Controller
{
    public function index()
    {
        return redirect()->route('billings.customers');
    }

    public function customers()
    {
        return view('billings.customers.index');
    }

    public function customerBillsEdit(Customer $customer)
    {
        $latestBill = Bill::where('billing_profile_id', $customer->billing_profile_id)->where('customer_id', $customer->id)->orderBy('period_end', 'desc')->first();
        $lastestLastDate = $latestBill
            ? Carbon::parse($latestBill['period_end'])->format('Y-m-d')
            : Carbon::now()->subYear();

        return view('billings.customers.bills', [
            'customer' => $customer,
            'lastBillEndDate' => $lastestLastDate
        ]);
    }

    public function customerBillsDataTable(Request $request, Customer $customer)
    {
        $sortDirection = Arr::get($request->input('order'), '0.dir', 'desc');
        $tableColumnName = Arr::get(
            $request->input('columns'),
            $request->input('order')[0]['column'] . '.' . 'name',
            'period_end'
        );

        $term = $request->input('search.value');

        $billsCollection = $customer->bills()
            ->orderBy($tableColumnName, $sortDirection);

        if ($term) {
            $totalBillsCount = $customer->bills()->count();
            $billsCount = $billsCollection->count();
        } else {
            $totalBillsCount = $billsCollection->count();
            $billsCount = $totalBillsCount;
        }

        $bills = $billsCollection->skip($request->get('start'))->limit($request->get('length'))->get();
        $billsCollection = CustomerBillsTableResource::collection($bills);

        return response()->json([
            'data' => $billsCollection,
            'recordsTotal' => $totalBillsCount,
            'recordsFiltered' => $billsCount
        ]);
    }

    public function customerBillItems(Customer $customer, Bill $bill)
    {
        return view('billings.customers.billItems', [
            'bill' => $bill,
            'customer' => $customer,
            'adHocs' => BillingFee::where('type', 'ad_hoc')->get(),
            'shipping_carriers' => ShippingCarrier::pluck('name', 'id'),
            'shipping_methods' => ShippingMethod::pluck('name', 'id')
        ]);
    }

    public function bills()
    {
        return view('billings.bills.index');
    }

    public function billsDataTable(Request $request)
    {
        $sortDirection = Arr::get($request->input('order'), '0.dir', 'desc');
        $tableColumnName = Arr::get(
            $request->input('columns'),
            $request->input('order')[0]['column'] . '.' . 'name',
            'period_end'
        );

        $term = $request->input('search.value');

        $billsCollection = Bill::query()->orderBy($tableColumnName, $sortDirection)
            ->whereIn('customer_id', auth()->user()->customerIds());

        if ($term) {
            $totalBillsCount = Bill::count();
            $billsCount = $billsCollection->count();
        } else {
            $totalBillsCount = $billsCollection->count();
            $billsCount = $totalBillsCount;
        }

        $bills = $billsCollection->skip($request->get('start'))->limit($request->get('length'))->get();
        $billsCollection = BillsTableResource::collection($bills);

        return response()->json([
            'data' => $billsCollection,
            'recordsTotal' => $totalBillsCount,
            'recordsFiltered' => $billsCount
        ]);
    }

    public function billingProfiles()
    {
        return view('billings.billing_profiles.index');
    }

    public function reconcile()
    {
        return view('billings.reconcile.index');
    }

    public function exports()
    {
        return view('billings.exports.index');
    }

    public function productProfiles()
    {
        return view('billings.product_profiles.index', [
            'customers' => Customer::whereIn('id', auth()->user()->customerIds())->get()
        ]);
    }

    public function unbilled(Bill $bill)
    {
        return view('billings.customers.unbilled', [
            'billId' => $bill->id
        ]);
    }

    public function unBilledShipments(Request $request, Bill $bill)
    {
        return response()->json(BillComponent::unBilledShipments($request, $bill));
    }

    public function unBilledPurchaseOrders(Request $request,Bill $bill)
    {
        return response()->json(BillComponent::unBilledPurchaseOrders($request, $bill));
    }

    public function unBilledPurchaseOrderItems(Request $request,Bill $bill)
    {
        return response()->json(BillComponent::unBilledPurchaseOrderItems($request, $bill));
    }

    public function unBilledLocations(Request $request,Bill $bill)
    {
        return response()->json(BillComponent::unBilledLocations($request, $bill));
    }

    public function unBilledReturnItems(Request $request,Bill $bill)
    {
        return response()->json(BillComponent::unBilledReturnItems($request, $bill));
    }

    public function unBilledPackages(Request $request,Bill $bill)
    {
        return response()->json(BillComponent::unBilledPackages($request, $bill));
    }

    public function unBilledPackageItems(Request $request,Bill $bill)
    {
        return response()->json(BillComponent::unBilledPackageItems($request, $bill));
    }

    public function unBilledInventoryChanges(Request $request,Bill $bill)
    {
        return response()->json(BillComponent::unBilledInventoryChanges($request, $bill));
    }
}

resources/views/billings/old/customer_info.blade.php
<div class="container-fluid">
    <div class="row">
        <div class="col-4">
            <ul class="list-unstyled">
                <li class="text-muted">
                    {{__('Customer Name')}}: {{$customer->contactInformation->name}}
                </li>
                <li class="text-muted">
                    {{__('Company Name')}}: {{$customer->contactInformation->company_name}}
                </li>
                <li class="text-muted">
                    {{__('Adress')}}: {{$customer->contactInformation->address}}
                </li>
                <li class="text-muted">
                    {{__('Adress 2')}}: {{$customer->contactInformation->address2}}
                </li>
                <li class="text-muted">
                    {{__('Zip')}}: {{$customer->contactInformation->zip}}
                </li>
                <li class="text-muted">
                    {{__('City')}}: {{$customer->contactInformation->city}}
                </li>
                <li class="text-muted">
                    {{__('Email')}}: {{$customer->contactInformation->email}}
                </li>
                <li class="text-muted">
                    {{__('Phone')}}: {{$customer->contactInformation->phone}}
                </li>
            </ul>
            <ul class="list-unstyled">
                <li class="text-muted">
                    <form method="post" action="{{ route('billing.update_customer',['customerId' => $customer->id]) }}" autocomplete="off" enctype="multipart/form-data">
                        @csrf
                        <div class="d-inline-block w-75">
                            <select name="billing_profile_id" id="input-role_id" class="form-control d-inline-block " data-toggle="select" data-placeholder="">
                                @foreach($billingProfiles as $billingProfile)
                                    <option value="{{$billingProfile->id}}" {{$customer->billing_profile_id === $billingProfile->id ? 'selected' : ''}}>{{$billingProfile->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <button class="btn btn-primary edit d-inline-block" > {{__('Update')}} </button>
                    </form>
                </li>
            </ul>
        </div>
    </div>
</div>

resources/views/billings/old/index.blade.php
@extends('layouts.app', ['title' => __('Billings'), 'submenu' => 'billings.old.menu'])

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                @include('alerts.success')
                @include('alerts.errors')
            </div>
        </div>
        <div class="row">
            <div class="col col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-6">
                                <h3 class="mb-0">{{ __('Billings') }}</h3>
                            </div>
                            <div class="col-6 text-right">
                                @include('shared.modals.showHideTableColumns')
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        @include('alerts.success', ['class' => 'mt-2 mb-1'])
                        @include('alerts.errors', ['class' => 'mt-2 mb-1'])
                    </div>
                    <div class="table-responsive p-0">
                        <table class="table align-items-center table-hover col-12 p-0" id="billing-table" style="width: 100% !important;">
                            <thead class=""></thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection
@push('js')
    <script>
        new Preview();
        new Billing();
    </script>
@endpush

resources/views/billings/old/menu.blade.php
<li class="submenu {{ $class ?? '' }}" data-submenu="billings.menu">
    <ul>
        <li class="nav-item d-none">
            <a href="{{ route('invoices.index') }}" class="nav-link">
                <i class="nc-icon nc-single-folded-content text-gray"></i>
                <span class="nav-link-text text-gray">{{ __('Manage Invoices') }}</span>
            </a>
        </li>
        <li class="nav-item d-none">
            <a href="{{ route('invoice_statuses.index') }}" class="nav-link">
                <i class="nc-icon nc-single-folded-content text-gray"></i>
                <span class="nav-link-text text-gray">{{ __('Invoice Statuses') }}</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('billing_profiles.index') }}" class="nav-link">
                <i class="nc-icon nc-single-folded-content text-gray"></i>
                <span class="nav-link-text text-gray">{{ __('Billing Profiles') }}</span>
            </a>
        </li>
    </ul>
</li>

resources/views/billings/old/preview.blade.php
<h3 class="mb-3">{{__('Billing')}}:</h3>
<ul class="list-group mb-3">
    <li class="list-group-item">{{__('Name')}}: <strong>{{$customer->contactInformation->name}}</strong></li>
    <li class="list-group-item">{{__('Billing Profile')}}:
        <strong>
            <a href="{{route('billing_profiles.edit', ['billingProfile' => $customer->billingProfile ?? null])}}">{{$customer->billingProfile->name}}</a>
        </strong>
    </li>
    <li class="list-group-item">{{__('Company Name')}}: <strong>{{$customer->contactInformation->company_name}}</strong></li>
    <li class="list-group-item">{{__('Invoice Count')}}: <strong>{{$customer->invoice->count()}}</strong></li>
</ul>

resources/views/billings/old/show.blade.php
@extends('layouts.app', ['title' => __('Billing Management')])

@section('content')

    <div class="container-fluid mt--6">
        <div class="col-12 mt-2">
            @include('alerts.success')
            @include('alerts.errors')
        </div>
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Customer Billings') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('orders.index') }}" class="btn btn-secondary btn-sm">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        @include('billings.old.customer_info')

                        <form method="post" action="{{ route('billings.generate_invoice',['customerId' => $customer->id]) }}" autocomplete="off" enctype="multipart/form-data">
                            @csrf
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-3">
                                        <button class="btn btn-primary edit" > Generate Invoice </button>
                                    </div>
                                </div>
                            </div>
                        </form>

                        <div class="table-responsive">
                            <input type="hidden" id="customer-id" value="{{$customer->id}}">
                            <table class="table align-items-center table-hover col-12" id="customer-invoices-table">
                                <thead class=""></thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection
@push('js')
    <script>
        new Billing();
    </script>
@endpush