routes/web.php
    Route::post('customers/settings', 'CustomerController@updateSettings')->name('customers.update_settings');
    Route::resource('customers', 'CustomerController');

    Route::get('products/data_table', 'ProductController@dataTable')->name('products.data_table');
    Route::get('products/{product}/preview', 'ProductController@preview')->name('products.preview');
    Route::get('products/{product}/editable_preview', 'ProductController@editablePreview')->name('products.editable_preview');
    Route::get('product/delete_product_image', 'ProductController@deleteProductImage')->name('products.delete_product_image');
    Route::get('products/filter_customers', 'ProductController@filterCustomers')->name('products.filter_customers');
    Route::get('products/export', 'ProductController@export')->name('products.export');
    Route::post('products/import', 'ProductController@import')->name('products.import');
    Route::get('products/change_log', 'ProductController@changeLog')->name('products.change_log');
    Route::get('products/log_data_table/{product_id?}', 'ProductController@changeLogDataTable')->name('products.log_data_table');
    Route::resource('products', 'ProductController');

    Route::get('orders/filter_customers', 'OrderController@filterCustomers')->name('orders.filter_customers');
    Route::get('orders/filter_products/{customer}', 'OrderController@filterProducts')->name('orders.filter_products');
    Route::get('orders/data_table', 'OrderController@dataTable')->name('orders.data_table');
    Route::get('orders/dashboard-data-table', 'OrderController@dashboardDataTable')->name('orders.dashboard_data_table');
    Route::get('orders/orders_by_cities', 'HomeController@ordersByCities');
    Route::get('orders/orders_by_cities_limited', 'HomeController@ordersByCities');
    Route::get('orders/orders_by_country', 'HomeController@ordersByCountry');
    Route::get('orders/orders_received_count', 'HomeController@ordersReceivedCalc');
    Route::get('orders/orders_shipped_count', 'HomeController@shipmentsCalc');

    Route::get('orders/{order}/carrier/{carrier}', 'OrderController@carrier');
    Route::get('orders/{order}/carriers', 'OrderController@carriers');
    Route::get('orders/{order}/preview', 'OrderController@preview')->name('orders.preview');
    Route::get('orders/{order}/editable_preview', 'OrderController@editablePreview')->name('orders.editable_preview');
    Route::get('orders/export', 'OrderController@export')->name('orders.export');
    Route::post('orders/import', 'OrderController@import')->name('orders.import');
    Route::get('orders/shipping_methods/{customer}', 'OrderController@shippingMethods')->name('orders.shipping_methods');
    Route::get('orders/total_orders_by_statuses', 'OrderController@totalOrdersByStatuses');
    Route::post('orders/{order}/cancel', 'OrderController@cancel')->name('orders.cancel');
    Route::post('orders/{order}/reship', 'OrderController@reship')->name('orders.reship');
    Route::get('orders/change_log', 'OrderController@changeLog')->name('orders.change_log');
    Route::get('orders/log_data_table/{order_id?}', 'OrderController@changeLogDataTable')->name('orders.log_data_table');
    Route::resource('orders', 'OrderController');

    Route::get('purchase_orders/data_table', 'PurchaseOrderController@dataTable')->name('purchase_orders.data_table');
    Route::get('purchase_orders/filter_products/{supplier}', 'PurchaseOrderController@filterProducts')->name('purchase_orders.filter_products');
    Route::get('purchase_orders/filter_customers', 'PurchaseOrderController@filterCustomers')->name('purchase_orders.filter_customers');
    Route::get('purchase_orders/filter_locations', 'PurchaseOrderController@filterLocations')->name('purchase_orders.filter_locations');
    Route::get('purchase_orders/filter_warehouses/{customer}', 'PurchaseOrderController@filterWarehouses')->name('purchase_orders.filter_warehouses');
    Route::get('purchase_orders/filter_suppliers/{customer}', 'PurchaseOrderController@filterSuppliers')->name('purchase_orders.filter_suppliers');
    Route::get('purchase_orders/{purchase_order}/preview', 'PurchaseOrderController@preview')->name('purchase_orders.preview');
    Route::get('purchase_orders/{purchase_order}/editable_preview', 'PurchaseOrderController@editablePreview')->name('purchase_orders.editable_preview');
    Route::get('purchase_orders/export', 'PurchaseOrderController@export')->name('purchase_orders.export');
    Route::post('purchase_orders/import', 'PurchaseOrderController@import')->name('purchase_orders.import');
    Route::get('purchase_orders/coming_in', 'HomeController@purchaseOrdersCalc');
    Route::get('purchase_orders/quantity_calc', 'HomeController@purchaseOrdersQuantityCalc');
    Route::get('purchase_orders/total_purchase_orders_by_statuses', 'PurchaseOrderController@totalPurchaseOrdersByStatuses');
    Route::post('purchase_orders/{purchase_order}/cancel', 'PurchaseOrderController@cancel')->name('purchase_orders.cancel');
    Route::get('purchase_orders/auto_pending/{supplier}', 'PurchaseOrderController@autoPending')->name('purchase_orders.auto_pending');
    Route::get('purchase_orders/auto_all/{supplier}', 'PurchaseOrderController@autoAll')->name('purchase_orders.auto_all');
    Route::get('purchase_orders/auto_backordered/{supplier}', 'PurchaseOrderController@autoBackordered')->name('purchase_orders.auto_backordered');
    Route::get('purchase_orders/change_log', 'PurchaseOrderController@changeLog')->name('purchase_orders.change_log');
    Route::get('purchase_orders/log_data_table/{purchase_order_id?}', 'PurchaseOrderController@changeLogDataTable')->name('purchase_orders.log_data_table');

    Route::resource('purchase_orders', 'PurchaseOrderController');

    Route::get('returns/data_table', 'ReturnController@dataTable')->name('returns.data_table');
    Route::get('returns/filter_order_products/{order_id}', 'ReturnController@filterOrderProducts')->name('returns.filter_order_products');
    Route::get('returns/get_order_products/{order_id}', 'ReturnController@getOrderProducts')->name('returns.get_order_products');
    Route::get('returns/filter_orders/{customer}', 'ReturnController@filterOrders')->name('returns.filter_orders');
    Route::get('returns/filter_locations', 'ReturnController@filterLocations')->name('returns.filter_locations');
    Route::get('returns/{return}/preview', 'ReturnController@preview')->name('returns.preview');
    Route::get('returns/{return}/editable_preview', 'ReturnController@editablePreview')->name('returns.editable_preview');
    Route::get('returns/returns-count', 'HomeController@returnsCalc');
    Route::get('returns/total_returns_by_statuses', 'ReturnController@totalReturnsByStatuses');

    Route::resource('returns', 'ReturnController');

    Route::get('warehouses/data_table', 'WarehouseController@dataTable')->name('warehouse.data_table');
    Route::get('warehouses/{warehouse}/edit/location', 'WarehouseController@edit')->name('warehouses.edit_warehouse_location');
    Route::post('warehouses/{warehouse}/add_users', 'WarehouseController@addCustomers')->name('warehouse.add_customers');
    Route::get('warehouses/filter_customers', 'WarehouseController@filterCustomers')->name('warehouses.filter_customers');
    Route::get('warehouse-by-customer/{customer}', 'WarehouseController@getWarehouseByCustomer')->name('warehouse_by_customer');
    Route::resource('warehouses', 'WarehouseController', ['except' => ['show']]);

    Route::get('warehouses/{warehouse}/edit/location/create', 'LocationController@create')->name('warehouse_location.create');
    Route::post('warehouses/{warehouse}/edit/location/store', 'LocationController@store')->name('warehouse_location.store');
    Route::delete('warehouses/{warehouse}/edit/warehouse/location/{location}', 'LocationController@destroy')->name('warehouse_location.destroy');
    Route::get('warehouses/{warehouse}/edit/location/{location}', 'LocationController@edit')->name('warehouse_location.edit');
    Route::post('warehouses/{warehouse}/edit/location/{location}/update', 'LocationController@update')->name('warehouse_location.update');

    //    Session customer
    Route::get('forget', 'Controller@forgetCustomer')->name('controller.forget_customer');
    Route::get('customer/set/{id}', 'Controller@sessionSetCustomer')->name('controller.session_set_customer');

    Route::get('vendor-by-customer/{customer}', 'SupplierController@getVendorByCustomer')->name('vendor_by_customer');
    Route::get('vendors/data_table', 'SupplierController@dataTable')->name('vendors.data_table');
    Route::get('vendors/filter_customers', 'SupplierController@filterCustomers')->name('vendors.filter_customers');
    Route::resource('vendors', 'SupplierController');

    Route::get('profiles/webhook/filter_customers', 'WebhookController@filterCustomers')->name('webhook.filter_customers');
    Route::get('profiles/webhook/filter_users', 'WebhookController@filterUsers')->name('webhook.filter_users');
    Route::resource('profiles/webhook', 'WebhookController');

    Route::get('locations/data_table', 'LocationController@dataTable')->name('customer.data_table');
    Route::get('locations/{warehouse}', 'LocationController@index')->name('locations.index');
    Route::get('locations/filter_locations', 'LocationController@filterLocations')->name('locations.filter_locations');
    Route::get('locations/filter_products/{location?}', 'LocationController@filterProducts')->name('locations.filter_products');
    Route::post('locations/transfer/product/{location}', 'LocationController@transfer')->name('locations.transfer');
    Route::resource('locations', 'LocationController')->except(['create', 'store']);

    Route::get('inventory_logs/data_table', 'InventoryLogController@dataTable')->name('inventory_log.data_table');
    Route::resource('inventory_logs', 'InventoryLogController');

    Route::get('shipments/data_table', 'ShipmentController@dataTable')->name('shipment.data_table');

app/Http/Controllers/Api/SupplierController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Supplier;
use App\Models\UserRole;
use Illuminate\Http\Request;
use App\Http\Controllers\ApiController;
use App\Http\Resources\SupplierResource;
use App\Http\Resources\SupplierCollection;
use App\Http\Requests\Supplier\StoreBatchRequest;
use App\Http\Requests\Supplier\UpdateBatchRequest;
use App\Http\Requests\Supplier\DestroyBatchRequest;
use App\Http\Requests\SupplierProduct\StoreRequest as SupplierProductRequest;
use Illuminate\Http\Resources\Json\ResourceCollection;
use Illuminate\Support\Arr;

class SupplierController extends ApiController
{
    public function __construct()
    {
        $this->authorizeResource(Supplier::class);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customerIds = Auth()->user()->customerIds();

        $suppliers = Supplier::whereIn('customer_id', $customerIds)->paginate();

        return new SupplierCollection($suppliers);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreBatchRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBatchRequest $request)
    {
        return response()->json(
            new SupplierCollection(
                app()->supplier->storeBatch($request)
            )
        );
    }

    /**
     * Display the specified resource.
     *
     * @param  Supplier $supplier
     * @return \Illuminate\Http\Response
     */
    public function show(Supplier $supplier)
    {
        return new SupplierResource($supplier);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateBatchRequest $request
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBatchRequest $request)
    {
        return response()->json(
            new SupplierCollection(
                app()->supplier->updateBatch($request)
            )
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param DestroyBatchRequest $request
     * @return \Illuminate\Http\Response
     */
    public function destroy(DestroyBatchRequest $request)
    {
        return response()->json(
            new ResourceCollection(
                app()->supplier->destroyBatch($request)
            )
        );
    }

    public function products(SupplierProductRequest $request, Supplier $supplier)
    {
        return response()->json(
            new SupplierResource(
                app()->supplier->products($request, $supplier)
            )
        );
    }
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Supplier\DestroyRequest;
use App\Http\Requests\Supplier\StoreRequest;
use App\Http\Requests\Supplier\UpdateRequest;
use App\Http\Resources\SupplierTableResource;
use App\Models\Customer;
use App\Models\Supplier;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Auth;

class SupplierController extends Controller
{
    public function __construct()
    {
        // $this->authorizeResource(Supplier::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('supplier.index', [
            'hideColumns' => get_hidden_columns(Supplier::SETTINGS_HIDDEN_COLUMNS_KEY)
        ]);
    }

    public function dataTable(Request $request)
    {
        $sortDirection = Arr::get($request->input('order'), '0.dir', 'desc');
        $tableColumnName = Arr::get(
            $request->input('columns'),
            $request->input('order')[0]['column'] . '.' . 'name',
            'contact_informations.name'
        );

        $term = $request->input('search.value');

        $supplierCollection = app()->supplier->search($term)
            ->leftJoin('contact_informations AS customer_contact_information', function ($join) {
                $join->on('suppliers.customer_id', '=', 'customer_contact_information.object_id')
                    ->where('customer_contact_information.object_type', Customer::class);
            })
            ->leftJoin('contact_informations', function ($join) {
                $join->on('suppliers.id', '=', 'contact_informations.object_id')
                    ->where('contact_informations.object_type', Supplier::class);
            })
            ->select('*', 'suppliers.*')
            ->orderBy($tableColumnName, $sortDirection);

        if ($term) {
            $totalSupplierCount = Supplier::count();
            $supplierCount = $supplierCollection->count();
        } else {
            $totalSupplierCount = $supplierCollection->count();
            $supplierCount = $totalSupplierCount;
        }

        $suppliers = $supplierCollection->skip($request->get('start'))->limit($request->get('length'))->get();
        $supplierCollection = SupplierTableResource::collection($suppliers);

        return response()->json([
            'data' => $supplierCollection,
            'recordsTotal' => $totalSupplierCount,
            'recordsFiltered' => $supplierCount
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('supplier.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        app()->supplier->store($request);

        return redirect()->route('vendors.index')->withStatus(__('Supplier successfully created.'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Supplier $supplier
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Supplier $vendor)
    {
        return view('supplier.edit', ['supplier' => $vendor]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, Supplier $vendor)
    {
        app()->supplier->update($request, $vendor);

        return redirect()->back()->withStatus(__('Supplier successfully updated.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(DestroyRequest $request, Supplier $vendor)
    {
        app()->supplier->destroy($request, $vendor);

        return redirect()->route('vendors.index')->withStatus(__('Supplier successfully deleted.'));
    }

    public function filterCustomers(Request $request)
    {
        return app()->supplier->filterCustomers($request);
    }

    public function getVendorByCustomer(Customer $customer)
    {
        $suppliers = app()->supplier->getVendorByCustomer($customer);

        return $this->getDropDownList($suppliers);
    }
}

resources/views/supplier/create.blade.php
@extends('layouts.app', ['title' => __('Vendor Management'), 'icon' => '<i class="ci ci-receiving"></i>'])

@section('content')

    <div class="container-fluid">
        <form method="post" action="{{ route('vendors.store') }}" autocomplete="off">
            @csrf
            <div class="row">
                <div class="col col-12 {{ session($key ?? 'status') || !$errors->isEmpty() ? 'd-block' : 'd-none' }}">
                    <div class="card transparent">
                        @include('alerts.success')
                        @include('alerts.errors')
                        @include('alerts.ajax_error')
                    </div>
                </div>
                <div class="col col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="row align-items-center">
                                <div class="col-8">
                                    <h3 class="mb-0">{{ __('Add Vendor') }}</h3>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <h6 class="heading-small text-muted mb-4">{{ __('Vendor information') }}</h6>
                            @include('supplier.supplierInformationFields')
                        </div>
                        <div class="card-header pt-0 pb-0">
                            <div class="row align-items-center">
                                <div class="col">
                                    <h6 class="heading-small text-muted">{{ __('Product information') }}</h6>
                                </div>
                            </div>
                        </div>
                        <div class="card-body pb-0">
                            <fieldset>
                                <div class="row">
                                    <div class="col col-12 mb--2">
                                        @include('shared.forms.ajaxSelect', [
                                            'url' => route('orders.filter_products', ['customer' => session('customer_id') ?? old('customer_id')]),
                                            'name' => '',
                                            'required' => 'required',
                                            'className' => 'ajax-user-input product_id',
                                            'placeholder' => __('Search'),
                                            'label' => __('Search to add product')
                                        ])
                                    </div>
                                </div>
                            </fieldset>
                        </div>
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="col-12 table align-items-center table-flush">
                                    <thead class="">
                                    <tr>
                                        <th scope="col">{{ __('Products') }}</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody id="item_container">
                                    @if(count( old()['supplier_product']['products'] ?? [] ) > 0)
                                        @foreach(old()['supplier_product']['products'] as $key => $item)
                                            @php
                                                $product = App\Models\Product::find($item ?? null);
                                            @endphp
                                            @if($product)
                                                <tr class="order-item-fields {{ $item ? '':'d-none' }}">
                                                    <td style="white-space: unset">
                                                        <input type="hidden" class="product_supplier"
                                                               name="supplier_product[products][{{$key}}]"
                                                               value="{{$product['id']}}"
                                                        >
                                                        <span class="text-body product_name">{{$product['name']}}</span>
                                                    </td>
                                                    <td class="text-right">
                                                        <a class="btn btn-primary btn-sm text-white remove-item-button remove-supplier-item">
                                                            ×
                                                        </a>
                                                    </td>
                                                </tr>
                                            @else
                                                <tr class="order-item-fields d-none">
                                                    <td style="white-space: unset">
                                                        <input type="hidden" class="product_supplier" name="supplier_product[products][{{$key}}]">
                                                        <span class="text-body product_name"></span>
                                                    </td>
                                                    <td class="text-right">
                                                        <a class="btn btn-primary btn-sm text-white remove-item-button remove-supplier-item">
                                                            ×
                                                        </a>
                                                    </td>
                                                </tr>
                                            @endif
                                        @endforeach
                                    @else
                                        <tr class="order-item-fields d-none">
                                            <td style="white-space: unset">
                                                <input type="hidden" class="product_supplier" name="supplier_product[products][0]">
                                                <span class="text-body product_name"></span>
                                            </td>
                                            <td class="text-right">
                                                <a class="btn btn-primary btn-sm text-white remove-item-button remove-supplier-item">
                                                    ×
                                                </a>
                                            </td>
                                        </tr>
                                    @endif
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col col-12">
                    <div class="card transparent text-right">
                        <a href="{{ route('products.index') }}" class="btn btn-secondary">{{ __('Cancel') }}</a>
                        <button type="submit" class="btn btn-primary">{{ __('Submit') }}</button>
                    </div>
                </div>
            </div>
        </form>
        @include('layouts.footers.auth')
    </div>
@endsection

@push('js')
    <script>
        new SupplierForm();
    </script>
@endpush

resources/views/supplier/edit.blade.php
@extends('layouts.app', ['title' => __('Supplier Management'), 'icon' => '<i class="ci ci-receiving"></i>'])

@section('content')

    <div class="container-fluid">
        <form method="post" action="{{ route('vendors.update', [ 'supplier' => $supplier, 'id' => $supplier->id ]) }}" autocomplete="off">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col col-12 {{ session($key ?? 'status') || !$errors->isEmpty() ? 'd-block' : 'd-none' }}">
                    <div class="card transparent">
                        @include('alerts.success')
                        @include('alerts.errors')
                        @include('alerts.ajax_error')
                    </div>
                </div>
                <div class="col col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="row align-items-center">
                                <div class="col-8">
                                    <h3 class="mb-0">{{ __('Edit Vendor') }}</h3>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <h6 class="heading-small text-muted mb-4">{{ __('Vendor information') }}</h6>
                            @include('supplier.supplierInformationFields', [
                                'supplier' => $supplier
                            ])
                        </div>
                        <div class="card-header pt-0 pb-0">
                            <div class="row align-items-center">
                                <div class="col">
                                    <h6 class="heading-small text-muted">{{ __('Product information') }}</h6>
                                </div>
                            </div>
                        </div>
                        <div class="card-body pb-0">
                            <fieldset>
                                <div class="row">
                                    <div class="col col-12 mb--2">
                                        @include('shared.forms.ajaxSelect', [
                                            'url' => route('orders.filter_products', ['customer' => $supplier->customer->id]),
                                            'name' => '',
                                            'required' => 'required',
                                            'className' => 'ajax-user-input product_id',
                                            'placeholder' => __('Search'),
                                            'label' => __('Search to add product')
                                        ])
                                    </div>
                                </div>
                            </fieldset>
                        </div>
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <input type="hidden" id="supplier" value="{{$supplier->id}}">
                                <table class="col-12 table align-items-center table-flush">
                                    <thead class="">
                                    <tr>
                                        <th scope="col">{{ __('Products') }}</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody id="item_container">
                                    @if($supplier->products->count() == 0)
                                        <tr id="item_container" class="order-item-fields d-none">
                                            <td style="white-space: unset">
                                                <input type="hidden" class="product_supplier" name="supplier_product[products][0]">
                                                <span class="text-body product_name"></span>
                                                >
                                            </td>
                                            <td class="text-right">
                                                <a class="btn btn-primary btn-sm text-white remove-item-button remove-supplier-item">
                                                    ×
                                                </a>
                                            </td>
                                        </tr>
                                    @endif
                                    @foreach($supplier->products as $key => $product)
                                        <tr class="order-item-fields">
                                            <td style="white-space: unset">
                                                <input type="hidden" class="product_supplier"
                                                       name="supplier_product[products][{{$key}}]"
                                                       value="{{$product->id}}"
                                                >
                                                <span class="text-body product_name">{{'SKU: ' . $product->sku . ', NAME: ' . $product->name}}</span>

                                            </td>
                                            <td class="text-right">
                                                <a class="btn btn-primary btn-sm text-white remove-item-button remove-supplier-item">
                                                    ×
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col col-12">
                    <div class="card transparent text-right">
                        <a href="{{ route('vendors.index') }}" class="btn btn-secondary">{{ __('Cancel') }}</a>
                        <button type="submit" class="btn btn-primary">{{ __('Submit') }}</button>
                    </div>
                </div>
            </div>
        </form>
        @include('layouts.footers.auth')
    </div>
@endsection

@push('js')
    <script>
        new SupplierForm();
    </script>
@endpush